-- -- Thanks Thrasy :)
-- NDefines_Graphics.NAirGfx.MAX_MISSILE_BOMBING_SCENARIOS = 0
-- NDefines_Graphics.NAirGfx.MAX_BOMBING_SCENARIOS = 0
-- NDefines_Graphics.NAirGfx.MAX_PATROL_SCENARIOS = 0
-- NDefines_Graphics.NAirGfx.MAX_DOGFIGHTS_SCENARIOS = 0
-- NDefines_Graphics.NAirGfx.MAX_TRANSPORT_SCENARIOS = 0
-- NDefines_Graphics.NAirGfx.AIRPLANES_ANIMATION_GLOBAL_SPEED_PER_GAMESPEED = {0.3, 0.3, 0.3, 0.3, 0.3, 0.3}
-- NDefines_Graphics.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_MOVE = 0.02
-- NDefines_Graphics.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_TURN = 0.02
-- NDefines_Graphics.NMapMode.MAP_MODE_TERRAIN_TRANSPARENCY = 0.8
-- NDefines_Graphics.NMapMode.RADAR_ROTATION_SPEED = 0.0
-- NDefines_Graphics.NMapMode.AIR_RANGE_INDICATOR_ROTATION_SPEED = 0.0000
-- NDefines_Graphics.NGraphics.CAMERA_ZOOM_SPEED_DISTANCE_MULT = 20
-- NDefines_Graphics.NGraphics.MAPICON_GROUP_STRATEGIC_SIZE = 1000
-- NDefines_Graphics.NGraphics.MAP_ICONS_STATE_HUGE = 100
-- NDefines_Graphics.NGraphics.GRADIENT_BORDERS_FIELD_COUNTRY_REFRESH = 50
-- NDefines_Graphics.NGraphics.DECISION_MAP_ICON_DISTANCE_CUTOFF = 1000
-- NDefines_Graphics.NGraphics.PROVINCE_ANIM_TEXT_DISTANCE_CUTOFF = 200
-- NDefines_Graphics.NGraphics.AIRBASE_ICON_DISTANCE_CUTOFF = 800
-- NDefines_Graphics.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 600
-- NDefines_Graphics.NGraphics.RADAR_ICON_DISTANCE_CUTOFF = 500
-- NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {200, 500, 750}  -- At what camera distance the VP name text disappears.
-- NDefines_Graphics.NGraphics.VICTORY_POINTS_DISTANCE_CUTOFF = {250, 500, 750}
-- NDefines_Graphics.NGraphics.MAX_MESHES_LOADED_PER_FRAME = 5
-- NDefines_Graphics.NGraphics.DRAW_DETAILED_CUTOFF = 500
-- NDefines_Graphics.NInterface.GRIDBOX_ELEMENTS_INTERPOLATION_SPEED = 0.2
-- NDefines_Graphics.NGraphics.TREE_FADE_NEAR = 0
-- NDefines_Graphics.NGraphics.TREE_FADE_FAR = 0
-- NDefines_Graphics.NGraphics.RESOURCE_MAP_ICON_TEXT_CUTOFF = 1000
-- NDefines_Graphics.NGraphics.UNITS_DISTANCE_CUTOFF = 250
-- NDefines_Graphics.NGraphics.SHIPS_DISTANCE_CUTOFF = 200
-- NDefines_Graphics.NGraphics.UNIT_ARROW_DISTANCE_CUTOFF = 500
-- NDefines_Graphics.NGraphics.UNITS_ICONS_DISTANCE_CUTOFF = 500
-- NDefines_Graphics.NGraphics.NAVAL_COMBAT_DISTANCE_CUTOFF = 1000
-- NDefines_Graphics.NGraphics.ADJACENCY_RULE_DISTANCE_CUTOFF = 1000
-- NDefines_Graphics.NGraphics.LAND_COMBAT_DISTANCE_CUTOFF = 800
-- NDefines_Graphics.NGraphics.SUPPLY_ICON_DISTANCE_CUTOFF = 1500
-- NDefines_Graphics.NGraphics.PROV_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 300
-- NDefines_Graphics.NGraphics.STATE_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 600
-- NDefines_Graphics.NGraphics.GRADIENT_BORDERS_REFRESH_FREQ = 0.2
-- NDefines_Graphics.NGraphics.MAPICON_GROUP_PASSES = 5
-- NDefines_Graphics.NGraphics.DRAW_REFRACTIONS_CUTOFF = 0
-- NDefines_Graphics.NGraphics.WEATHER_DISTANCE_CUTOFF = 0
-- NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 100
-- NDefines_Graphics.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 300
-- NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 400
-- NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_AREA_HUGE = 250
-- NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 300
-- NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 0
-- NDefines_Graphics.NGraphics.CAPITAL_ICON_CUTOFF = 800					
-- NDefines_Graphics.NGraphics.DRAW_MAP_OBJECTS_CUTOFF = 250 					
-- NDefines_Graphics.NGraphics.MAP_BUILDINGS_SHRINK_DISTANCE = 100				
-- NDefines_Graphics.NGraphics.BLOOM_WIDTH = 0
-- NDefines_Graphics.NGraphics.BLOOM_SCALE = 0
-- NDefines_Graphics.NGraphics.BRIGHT_THRESHOLD = 0
-- NDefines_Graphics.NGraphics.EMISSIVE_BLOOM_STRENGTH = 0
-- NDefines_Graphics.NGraphics.DAY_NIGHT_FEATHER = 0.024
-- NDefines_Graphics.NGraphics.DRAW_SHADOWS_CUTOFF = 0
-- NDefines_Graphics.NGraphics.DRAW_SHADOWS_FADE_LENGTH = 0
-- NDefines_Graphics.NGraphics.DRAW_FOW_CUTOFF = 0
-- NDefines_Graphics.NGraphics.DRAW_FOW_FADE_LENGTH = 0
-- NDefines_Graphics.NGraphics.BORDER_WIDTH = 1


	NDefines_Graphics.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
	NDefines_Graphics.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
	NDefines_Graphics.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10
	NDefines_Graphics.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196
	NDefines_Graphics.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41
	NDefines_Graphics.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 24000
	NDefines_Graphics.NGraphics.RAILWAY_MAP_ARROW_COLOR_DEFAULT = { 0, 128, 0, 1.0 } -- green default railway maparrow color
	NDefines_Graphics.NGraphics.RAILWAY_MAP_ARROW_THIN_LEVEL_THRESHOLD = 1 -- Railway level 1 uses thin map arrow in supply map mode
	NDefines_Graphics.NGraphics.RAILWAY_MAP_ARROW_MEDIUM_LEVEL_THRESHOLD = 5 -- Railway level 2-3 uses medium map arrow in supply map mode
	NDefines_Graphics.NGraphics.RAILWAY_MAP_ARROW_THICK_LEVEL_THRESHOLD = 9 -- Railway level 4-5 uses thick map arrow in supply map mode
	NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_CAPITAL_CUTOFF_MAX = 1500.0 -- Capitals are special snowflakes, they need their own number
	NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {150, 250, 500} -- At what camera distance the VP name text disappears. 
	NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF_MAX = 800.0-- Max range for victory point text 
	NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF_MIN = 100.0 -- Min range for victory point text
	NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_DOT_CUTOFF_MIN = 100.0 -- Min range for victory point dot
	NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_DOT_CUTOFF_MAX = 1000.0 -- Max range for victory point dot